# Generated by Django 3.1.5 on 2021-01-18 00:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Название')),
                ('original_name', models.TextField(verbose_name='Оригинальное название')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('episode_count', models.IntegerField(null=True, verbose_name='Количество эпизодов')),
                ('current_episode', models.IntegerField(default=0, verbose_name='Текущий эпизод')),
                ('anilibria_link', models.URLField(verbose_name='Ссылка на страницу AniLibria.tv')),
                ('darklibria_link', models.URLField(verbose_name='Ссылка на страницу Dark-Libria.it')),
            ],
            options={
                'verbose_name': 'Тайтл',
                'verbose_name_plural': 'Аниме',
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Год')),
                ('season_year', models.TextField(choices=[('Зима', 'Зима'), ('Весна', 'Весна'), ('Лето', 'Лето'), ('Осень', 'Осень')], verbose_name='Время года')),
            ],
            options={
                'verbose_name': 'Сезон',
                'verbose_name_plural': 'Сезоны',
            },
        ),
        migrations.CreateModel(
            name='UserFavorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='watcher.anime', verbose_name='Аниме')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Избранное',
                'verbose_name_plural': 'Избранное',
            },
        ),
        migrations.CreateModel(
            name='AnimeDownloadLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(verbose_name='Ссылка')),
                ('date_added', models.DateTimeField(verbose_name='Дата добавления')),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='watcher.anime', verbose_name='ID аниме')),
            ],
            options={
                'verbose_name': 'Ссылка на скачивание',
                'verbose_name_plural': 'Ссылки на скачивание',
            },
        ),
        migrations.AddField(
            model_name='anime',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='watcher.season', verbose_name='Сезон'),
        ),
    ]
