# Generated by Django 3.1.5 on 2021-01-18 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watcher', '0002_auto_20210118_0328'),
    ]

    operations = [
        migrations.AddField(
            model_name='animedownloadlink',
            name='type',
            field=models.TextField(default='', verbose_name='Тип торрента'),
            preserve_default=False,
        ),
    ]
